create table public."Utenti" (
    id bigint generated by default as identity not null,
    "Email" text null,
    pwd text null,
    "Cognome" text null,
    "Nome" text null,
    "dataNascita" date null,
    "Sesso" public.Sesso null,
    token text null,
    note (private) text null,
    updated_at timestamp without time zone null,
    constraint Utenti_pkey primary key (id)
) TABLESPACE pg_default;

INSERT INTO
    "public"."Utenti" (
        "id",
        "Email",
        "pwd",
        "Cognome",
        "Nome",
        "dataNascita",
        "Sesso",
        "token",
        "note(private)",
        "updated_at"
    )
VALUES (
        '1',
        'gio@gmail.com',
        'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3',
        'B',
        'Giorgio',
        '2003-07-19',
        'Maschio',
        '7de274f4d57bd30dfc5281f61d207c248647a192813044635a118b6341c1a6ce626329c1d2d88fd27e0a45b915e4c6468894f17ad20d05102387a62c82eb0a72',
        null,
        '2025-07-03 12:21:24.349'
    ),
    (
        '2',
        '123@gmail.com',
        'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3',
        null,
        '123',
        '2004-12-08',
        'Femmina',
        'ee7801a53f48b9faa30e0e8553b0f796246661eab0de1ba41a03102202c98a5630a79640dfd8293d4f4965ec11821f640ca77979ca0a6b365f06372f81a3f602',
        null,
        '2025-07-02 09:19:01.628'
    ),
    (
        '3',
        '1234@gmail.com',
        'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3',
        null,
        '1234',
        '2004-12-08',
        'Maschio',
        'NO',
        null,
        null
    ),
    (
        '4',
        '12345@gmail.com',
        'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3',
        null,
        '12345',
        '2004-12-08',
        'Femmina',
        'NO',
        null,
        null
    ),
    (
        '5',
        'cheneso@gmail.com',
        '93a0c81b90b82178c04e655d74fcc24e3121665e226b8a89a520ef0e4199bb40',
        null,
        'che ne so',
        '2004-12-08',
        null,
        'NO',
        'Vediamo123$',
        null
    ),
    (
        '6',
        'ff@gmail.com',
        '65128631d600664484508acb330a44d3e1021dbe60a8692fe79d0f4af9f5798e',
        'F',
        'Francesco',
        '2004-12-08',
        'Maschio',
        'NO',
        'Francesco123$',
        null
    );
    